<?php

return [
    'default' => [
        'name' => 'Océano Profundo',
        'description' => 'Azul noche con acentos coral',
        'colors' => [
            'bg_primary'   => '#0a1628',
            'bg_secondary' => '#0f2744',
            'bg_section'   => '#112240',
            'bg_dark'      => '#0a0f1a',
            'bg_card'      => '#1a2744',
            'bg_card_hover' => '#243654',
            'text_primary' => '#e8f4f8',
            'text_secondary' => '#a8b2c8',
            'text_muted'   => '#6b7a94',
            'accent'       => '#ff6b6b',
            'accent_secondary' => '#00b4d8',
            'accent_green' => '#18833b',
            'accent_green_btn' => '#006847',
            'button_primary' => '#00b4d8',
            'button_hover'   => '#0096c7',
            'button_green'   => '#006847',
            'button_green_hover' => '#005236',
            'border'       => '#1d3a5f',
            'border_light' => '#243654',
            'border_hover' => '#2a4a7f',
            'overlay_dark' => 'rgba(10, 22, 40, 0.4)',
            'shadow'       => 'rgba(0, 0, 0, 0.9)',
        ],
    ],

    'costa' => [
        'name' => 'Costa Mexicana',
        'description' => 'Turquesa con arena y coral',
        'colors' => [
            'bg_primary'   => '#faf8f5',
            'bg_secondary' => '#e8f4f8',
            'bg_section'   => '#ffffff',
            'bg_dark'      => '#f0ece5',
            'bg_card'      => '#ffffff',
            'bg_card_hover' => '#f5f5f5',
            'text_primary' => '#1a3a4a',
            'text_secondary' => '#4a6b7a',
            'text_muted'   => '#7a8b9a',
            'accent'       => '#ff7f50',
            'accent_secondary' => '#00868b',
            'accent_green' => '#18833b',
            'accent_green_btn' => '#006847',
            'button_primary' => '#00868b',
            'button_hover'   => '#006b6b',
            'button_green'   => '#006847',
            'button_green_hover' => '#005236',
            'border'       => '#cce5e8',
            'border_light' => '#e0eff2',
            'border_hover' => '#b8d8e0',
            'overlay_dark' => 'rgba(250, 248, 245, 0.4)',
            'shadow'       => 'rgba(0, 0, 0, 0.15)',
        ],
    ],

    'mar_fresco' => [
        'name' => 'Mar Fresco',
        'description' => 'Blanco con verde mar y azul',
        'colors' => [
            'bg_primary'   => '#f5f9fa',
            'bg_secondary' => '#e0f4ff',
            'bg_section'   => '#ffffff',
            'bg_dark'      => '#e8f2f8',
            'bg_card'      => '#ffffff',
            'bg_card_hover' => '#f8fcfc',
            'text_primary' => '#1e3a4f',
            'text_secondary' => '#4a6b7a',
            'text_muted'   => '#6a8090',
            'accent'       => '#00a878',
            'accent_secondary' => '#0077b6',
            'accent_green' => '#00a878',
            'accent_green_btn' => '#0077b6',
            'button_primary' => '#0077b6',
            'button_hover'   => '#005f8f',
            'button_green'   => '#00a878',
            'button_green_hover' => '#008860',
            'border'       => '#b8d4e8',
            'border_light' => '#d0e8f4',
            'border_hover' => '#a0c8e0',
            'overlay_dark' => 'rgba(245, 249, 250, 0.4)',
            'shadow'       => 'rgba(0, 0, 0, 0.1)',
        ],
    ],

    'atardecer' => [
        'name' => 'Atardecer en el Mar',
        'description' => 'Azul noche con naranja coral',
        'colors' => [
            'bg_primary'   => '#1a1a2e',
            'bg_secondary' => '#16213e',
            'bg_section'   => '#1f2b47',
            'bg_dark'      => '#12182d',
            'bg_card'      => '#1a2540',
            'bg_card_hover' => '#243050',
            'text_primary' => '#edf2f7',
            'text_secondary' => '#8892a8',
            'text_muted'   => '#5a6278',
            'accent'       => '#ff9a3c',
            'accent_secondary' => '#00b4d8',
            'accent_green' => '#18833b',
            'accent_green_btn' => '#006847',
            'button_primary' => '#00b4d8',
            'button_hover'   => '#0096c7',
            'button_green'   => '#006847',
            'button_green_hover' => '#005236',
            'border'       => '#2a3a5f',
            'border_light' => '#344770',
            'border_hover' => '#3a5070',
            'overlay_dark' => 'rgba(26, 26, 46, 0.4)',
            'shadow'       => 'rgba(0, 0, 0, 0.8)',
        ],
    ],
];
